version: '3.8'

services:
  # API Gateway
  api-gateway:
    build:
      context: ./services/api-gateway
      target: development
    volumes:
      - ./services/api-gateway:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev

  # Auth Service
  auth-service:
    build:
      context: ./services/auth-service
      target: development
    volumes:
      - ./services/auth-service:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev

  # Binance API Service
  binance-api-service:
    build:
      context: ./services/binance-api
      target: development
    volumes:
      - ./services/binance-api:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev

  # MongoDB
  mongodb:
    ports:
      - "27017:27017"
    command: mongod --logpath=/dev/null # Disable logging
    volumes:
      - mongodb_data:/data/db

  # Redis
  redis:
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --loglevel warning
    volumes:
      - redis_data:/data

  # Nginx
  nginx:
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    ports:
      - "80:80"
      - "443:443"

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local 