services:
  # Backend API Service
  - type: web
    name: oriontrade-api
    env: node
    region: frankfurt
    plan: free
    buildCommand: cd backend && npm install && chmod +x init-db.sh
    startCommand: cd backend && ./init-db.sh && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: oriontrade-db
          property: connectionString

  # Frontend Static Site
  - type: web
    name: oriontrade-app
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: https://oriontrade-api.onrender.com/api

# Database
databases:
  - name: oriontrade-db
    region: frankfurt
    plan: free
    databaseName: oriontrade
    user: oriontrade_user 