name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017
      redis:
        image: redis:7.0-alpine
        ports:
          - 6379:6379

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linting
      run: npm run lint

    - name: Run tests
      run: npm run test
      env:
        NODE_ENV: test
        MONGODB_URI: mongodb://localhost:27017/quickytrade_test
        REDIS_HOST: localhost
        REDIS_PORT: 6379
        JWT_SECRET: test_jwt_secret
        BINANCE_API_KEY: test_api_key
        BINANCE_API_SECRET: test_api_secret

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push API Gateway
      uses: docker/build-push-action@v2
      with:
        context: ./services/api-gateway
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/quickytrade-api-gateway:latest

    - name: Build and push Auth Service
      uses: docker/build-push-action@v2
      with:
        context: ./services/auth-service
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/quickytrade-auth-service:latest

    - name: Build and push Binance API Service
      uses: docker/build-push-action@v2
      with:
        context: ./services/binance-api
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/quickytrade-binance-api:latest

    - name: Build and push Nginx
      uses: docker/build-push-action@v2
      with:
        context: ./nginx
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/quickytrade-nginx:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v2

    - name: Deploy to production
      run: |
        echo "Deploying to production..."
        # Add deployment steps here 