name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v3.0.0
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push API Gateway
        uses: docker/build-push-action@v2
        with:
          context: ./services/api-gateway
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/quickytrade-api-gateway:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/quickytrade-api-gateway:${{ github.ref_name }}

      - name: Build and push Auth Service
        uses: docker/build-push-action@v2
        with:
          context: ./services/auth-service
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/quickytrade-auth-service:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/quickytrade-auth-service:${{ github.ref_name }}

      - name: Build and push Binance API Service
        uses: docker/build-push-action@v2
        with:
          context: ./services/binance-api
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/quickytrade-binance-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/quickytrade-binance-api:${{ github.ref_name }}

      - name: Build and push Nginx
        uses: docker/build-push-action@v2
        with:
          context: ./nginx
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/quickytrade-nginx:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/quickytrade-nginx:${{ github.ref_name }}

      - name: Deploy to production
        if: success()
        run: |
          echo "Deploying version ${{ github.ref_name }} to production..."
          # Add deployment steps here 